# Generated by Django 5.0.4 on 2024-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='users/profile_images/default.jpg', upload_to='users/profile_images'),
        ),
    ]
