# Generated by Django 5.0.4 on 2024-10-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friends',
            new_name='subscribers',
        ),
    ]
