# Generated by Django 5.0.4 on 2024-10-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_friends_profile_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='users.profile'),
        ),
    ]
