# Generated by Django 5.0.4 on 2024-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_subscribers_profile_subscribed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, to='users.profile'),
        ),
    ]
