# Generated by Django 5.0.4 on 2025-04-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_subscribed_to_followrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hello world!'),
        ),
    ]
