# Generated by Django 5.0.4 on 2024-04-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('polls', '0001_initial'), ('polls', '0002_delete_choice_delete_question')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
